/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Database;
import java.awt.Color;
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author malith
 */
public class ItemSalesReport extends javax.swing.JFrame {

    /**
     * Creates new form ItemSalesReport
     */
    public ItemSalesReport() {
        initComponents();
        setBackground(new Color (0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new view.PanelBorder();
        StockReportClose = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItemSalesReport = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtItemNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtItemName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtItemSalesReportFromDate = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        txtItemSalesReportToDate = new com.toedter.calendar.JDateChooser();
        btnItemSalesReportSearch = new javax.swing.JButton();
        btnItemSalesReportViewAll = new javax.swing.JButton();
        btnItemSalesReportClear = new javax.swing.JButton();
        btnItemSalesReportPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        StockReportClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/closeLogin.png"))); // NOI18N
        StockReportClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StockReportCloseMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("   Item Sales Report");

        tblItemSalesReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Invoice No", "Qty Purchased", "Item Amount", "Discount", "Total Amount"
            }
        ));
        jScrollPane1.setViewportView(tblItemSalesReport);

        jLabel2.setText("Enter Item Number");

        jLabel3.setText("Item Name :");

        txtItemName.setText("--------------------------");

        jLabel5.setText("From");

        jLabel6.setText("To");

        btnItemSalesReportSearch.setBackground(new java.awt.Color(51, 153, 255));
        btnItemSalesReportSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnItemSalesReportSearch.setText("Search");
        btnItemSalesReportSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemSalesReportSearchActionPerformed(evt);
            }
        });

        btnItemSalesReportViewAll.setBackground(new java.awt.Color(0, 102, 102));
        btnItemSalesReportViewAll.setForeground(new java.awt.Color(255, 255, 255));
        btnItemSalesReportViewAll.setText("View All");
        btnItemSalesReportViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemSalesReportViewAllActionPerformed(evt);
            }
        });

        btnItemSalesReportClear.setBackground(new java.awt.Color(255, 0, 0));
        btnItemSalesReportClear.setForeground(new java.awt.Color(255, 255, 255));
        btnItemSalesReportClear.setText("Clear");
        btnItemSalesReportClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemSalesReportClearActionPerformed(evt);
            }
        });

        btnItemSalesReportPrint.setBackground(new java.awt.Color(51, 51, 255));
        btnItemSalesReportPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnItemSalesReportPrint.setText("Print");
        btnItemSalesReportPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemSalesReportPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1114, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StockReportClose))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 947, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelBorder1Layout.createSequentialGroup()
                                        .addComponent(txtItemNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(77, 77, 77)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelBorder1Layout.createSequentialGroup()
                                        .addComponent(txtItemSalesReportFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtItemSalesReportToDate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(41, 41, 41)
                                .addComponent(btnItemSalesReportSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnItemSalesReportClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnItemSalesReportViewAll)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnItemSalesReportPrint)
                .addGap(143, 143, 143))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(StockReportClose))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtItemNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtItemName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtItemSalesReportFromDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtItemSalesReportToDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnItemSalesReportSearch)
                        .addComponent(btnItemSalesReportClear)
                        .addComponent(btnItemSalesReportViewAll)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnItemSalesReportPrint)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void StockReportCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockReportCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_StockReportCloseMouseClicked

    private void btnItemSalesReportSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemSalesReportSearchActionPerformed
        // TODO add your handling code here:
        String fromDate = String.valueOf(txtItemSalesReportFromDate.getDate());
        String toDate = String.valueOf(txtItemSalesReportToDate.getDate());
        if(fromDate.equals("null") && toDate.equals("null"))
        {
            JOptionPane.showMessageDialog(this, "Date is Empty select date and search again", "Date is Empty", JOptionPane.WARNING_MESSAGE);
        }
        else if(!txtItemNumber.getText().equals(""))
        {
            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            DefaultTableModel tbmodel = (DefaultTableModel)tblItemSalesReport.getModel();
            tbmodel.setRowCount(0);

            Database db = new Database();
            int i = db.credential_check("select * from tb_item where INO = '"+txtItemNumber.getText()+"'");
            if(i==1)
            {
                ResultSet rs1 = db.selectData("select * from tb_item where INO = '"+txtItemNumber.getText()+"'");
                if(rs1!=null)
                {
                    try {
                        while(rs1.next())
                        {
                            txtItemName.setText(rs1.getString("IName"));
                        }
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "Item Data cannot be loaded try again", "Cannot load", JOptionPane.WARNING_MESSAGE);
                    }
                }

                ResultSet rs2 = db.selectData("SELECT Date,InvoiceNO,QtyPurchased,IAmount,DiscountRate,TotAmount FROM tb_invoice,tb_itemininvoice WHERE tb_invoice.InvoiceNO=tb_itemininvoice.InvNO AND QtyPurchased >0 AND INO="+txtItemNumber.getText()+" AND Date Between '"+df.format(txtItemSalesReportFromDate.getDate())+"' AND '"+df.format(txtItemSalesReportToDate.getDate())+"' ORDER BY invoiceNO");
                if(rs2!=null)
                {
                    try {
                        while(rs2.next())
                        {
                            String date = String.valueOf(rs2.getDate("Date"));
                            String invoiceNo = String.valueOf(rs2.getInt("InvoiceNO"));
                            String qtyPurchased = String.valueOf(rs2.getInt("QtyPurchased"));
                            String iAmount = String.valueOf(rs2.getDouble("IAmount"));
                            String dRate = String.valueOf(rs2.getDouble("DiscountRate"));
                            String totAmount = String.valueOf(rs2.getDouble("TotAmount"));

                            String[] tbData = {date,invoiceNo,qtyPurchased,iAmount,dRate,totAmount};

                            tbmodel.addRow(tbData);
                        }
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "Item Sale Data cannot be loaded try again", "Cannot load", JOptionPane.WARNING_MESSAGE);
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "No Data Found", "Cannot load", JOptionPane.WARNING_MESSAGE);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "No Such Item Found Check item number and search again", "No Item Found", JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Enter Item Number to Search Item", "Item Number is Empty", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnItemSalesReportSearchActionPerformed

    private void btnItemSalesReportViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemSalesReportViewAllActionPerformed
        // TODO add your handling code here:
        if(!txtItemNumber.getText().equals(""))
        {
            DefaultTableModel tbmodel = (DefaultTableModel)tblItemSalesReport.getModel();
            tbmodel.setRowCount(0);

            Database db = new Database();
            int i = db.credential_check("select * from tb_item where INO = '"+txtItemNumber.getText()+"'");
            if(i==1)
            {
                ResultSet rs1 = db.selectData("select * from tb_item where INO = '"+txtItemNumber.getText()+"'");
                if(rs1!=null)
                {
                    try {
                        while(rs1.next())
                        {
                            txtItemName.setText(rs1.getString("IName"));
                        }
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "Item Data cannot be loaded try again", "Cannot load", JOptionPane.WARNING_MESSAGE);
                    }
                }
                
                ResultSet rs2 = db.selectData("SELECT Date,InvoiceNO,QtyPurchased,IAmount,DiscountRate,TotAmount FROM tb_invoice,tb_itemininvoice WHERE tb_invoice.InvoiceNO=tb_itemininvoice.InvNO AND QtyPurchased >0 AND INO='"+txtItemNumber.getText()+"' ORDER BY invoiceNO");
                if(rs2!=null)
                {
                    try {
                        while(rs2.next())
                        {
                            String date = String.valueOf(rs2.getDate("Date"));
                            String invoiceNo = String.valueOf(rs2.getInt("InvoiceNO"));
                            String qtyPurchased = String.valueOf(rs2.getInt("QtyPurchased"));
                            String iAmount = String.valueOf(rs2.getDouble("IAmount"));
                            String dRate = String.valueOf(rs2.getDouble("DiscountRate"));
                            String totAmount = String.valueOf(rs2.getDouble("TotAmount"));
                            
                            String[] tbData = {date,invoiceNo,qtyPurchased,iAmount,dRate,totAmount};

                            tbmodel.addRow(tbData);
                        }
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, ex+" Item Sale Data cannot be loaded try again", "Cannot load", JOptionPane.WARNING_MESSAGE);
                    }
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "No Such Item Found Check item number and search again", "No Item Found", JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Enter Item Number to Search Item", "Item Number is Empty", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnItemSalesReportViewAllActionPerformed

    private void btnItemSalesReportClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemSalesReportClearActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tbmodel = (DefaultTableModel)tblItemSalesReport.getModel();
        tbmodel.setRowCount(0);
        txtItemNumber.setText(null);
        txtItemName.setText("--------------------------");        
    }//GEN-LAST:event_btnItemSalesReportClearActionPerformed

    private void btnItemSalesReportPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemSalesReportPrintActionPerformed
        // TODO add your handling code here:
        if(tblItemSalesReport.getRowCount()<=0)
        {
            JOptionPane.showMessageDialog(this, "Report Data Seems Empty Printing not Available","Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String fDate = String.valueOf(txtItemSalesReportFromDate.getDate());
            String eDate = String.valueOf(txtItemSalesReportToDate.getDate());
            String date = "";
            if(fDate.equals("null") && eDate.equals("null"))
            {
                date = "";
            }
            else
            {
                fDate = df.format(txtItemSalesReportFromDate.getDate());
                eDate = df.format(txtItemSalesReportToDate.getDate());
                date = "<p>From/To</p></td> <td><p>"+fDate+"/"+eDate+"</p>";
            }
            String aboutText="<tr style=\"border : solid 1pt #000000; border-collapse: collapse;\"> <td><p>Item No/Name</p></td> <td><p>"+txtItemNumber.getText()+"/"+txtItemName.getText()+"</p></td> <td>"+date+"</td> </tr>\n";
            printReport(aboutText);
        }
    }//GEN-LAST:event_btnItemSalesReportPrintActionPerformed

    private String username="";
    public void setUserName(String uName)
    {
        username = uName;
    }
    
    private void printReport(String about)
    {
        Date now = new Date();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String itemData = "";
        DecimalFormat decf = new DecimalFormat("0.00");
        int qtyPurchased = 0;
        double totSale = 0.0;
        double totReturn = 0.0;
        double netSale = 0.0;
        for(int c=0; c<tblItemSalesReport.getRowCount();c++)
        {
            qtyPurchased = qtyPurchased + Integer.parseInt(tblItemSalesReport.getValueAt(c, 2).toString());
            totSale = totSale + Double.parseDouble(tblItemSalesReport.getValueAt(c, 3).toString());
            totReturn = totReturn + Double.parseDouble(tblItemSalesReport.getValueAt(c, 4).toString());
            netSale = netSale + Double.parseDouble(tblItemSalesReport.getValueAt(c, 5).toString());
            
            if(itemData.equals(""))
            {
                itemData = "<tr><td><p>"+tblItemSalesReport.getValueAt(c, 0).toString()+"</p></td><td><p>"+tblItemSalesReport.getValueAt(c, 1).toString()+"</p></td><td><p>"+tblItemSalesReport.getValueAt(c, 2).toString()+"</p></td><td><p>"+tblItemSalesReport.getValueAt(c, 3).toString()+"</p></td><td><p>"+tblItemSalesReport.getValueAt(c, 4).toString()+"</p></td><td><p>"+tblItemSalesReport.getValueAt(c, 5).toString()+"</p></td></tr>\n";
            }  
            else
            {
                itemData = itemData + "<tr><td><p>"+tblItemSalesReport.getValueAt(c, 0).toString()+"</p></td><td><p>"+tblItemSalesReport.getValueAt(c, 1).toString()+"</p></td><td><p>"+tblItemSalesReport.getValueAt(c, 2).toString()+"</p></td><td><p>"+tblItemSalesReport.getValueAt(c, 3).toString()+"</p></td><td><p>"+tblItemSalesReport.getValueAt(c, 4).toString()+"</p></td><td><p>"+tblItemSalesReport.getValueAt(c, 5).toString()+"</p></td></tr>\n";
            }
        }
        String reportText = "<html>\n" +
                            "    <head>\n" +
                            "        <style>\n" +
                            "            p{font-family: 'Times New Roman', Times, serif;font-size: 11pt; text-align: left;}\n" +
                            //"            td {border : solid 1pt #000000; border-collapse: collapse;}\n" +
                            "            table{border : solid 1pt #000000; border-collapse: collapse;}\n" +
                            "        </style>\n" +
                            "    </head>\n" +
                            "    <body>\n" +
                            "        <table style=\"width: 100%;\">\n" +
                            "            <tr><td><h1 style=\"font-family: 'Times New Roman', Times, serif; font-size: 18pt; text-align: center;\">Item Details Report</h1></td></tr>\n" +
                            "            <tr aria-rowspan=\"3\">\n" +
                            "                <td><p>Multi Engineering Services Lanka Private Limited<br>No.466/7A Thapowanaya Road, Aggona<br>Sri Lanka.<br>Tel : 0112 794 959, 0114 558 559</p></td>\n" +
                            "            </tr>\n" +
                            //"            <tr><td><p style=\"text-align: center;\">Annual Sales Report<!--report name--></p></td></tr>\n" +
                            "\n" +
                            "            <!--report header details starts here-->\n" +
                            "            <tr>\n" +
                            "                <td>\n" +
                            "                    <table style=\"width: 100%;\">\n" +
                            "                        <tr style=\"border : solid 1pt #000000; border-collapse: collapse;\"> <td><p>Generated By,</p></td> <td><p>"+username+"</p></td> <td><p>Date : </p></td> <td><p>"+df.format(now)+"</p></td> </tr>\n" +
                            "                        "+about+"" +
                            "                    </table>\n" +
                            "                </td>\n" +
                            "            </tr>\n" +
                            "            <tr><td style=\"height: 12pt;\"><p></p></td></tr>\n" +
                            "\n" +
                            "            <!--data table starts here-->\n" +
                            "            <tr>\n" +
                            "                <td>\n" +
                            "                    <table style=\"width: 100%;\">\n" +
                            "                        <tr style=\"border : solid 1pt #000000; border-collapse: collapse;\"><td ><p>Date</p></td><td ><p>Invoice No</p></td><td><p>Qty Purchased</p></td><td><p>Item Amount<br>(LKR)</p></td><td><p>All Discount<br>(LKR)</p></td><td><p>Total Amount<br>(LKR)</p></td></tr>\n" +
                            "                        <!--item data comes here!-->\n" +
                            "                       "+itemData+" " +
                            "\n" +
                            "                        <!--finishes here-->\n" +
                            "                        <tr><td colspan=\"2\"><p style=\"text-align: right;\">Total : </p></td><td><p>"+qtyPurchased+"</p></td><td><p>"+decf.format(totSale)+"</p></td><td><p>"+decf.format(totReturn)+"</p></td><td><p>"+decf.format(netSale)+"</p></td></tr>\n" +
                            "                    </table>\n" +
                            "                </td>\n" +
                            "            </tr>\n" +
                            "\n" +
                            "            <tr><td><br><p style=\"text-align: right;\">Certified by,<br><br>-----------------------</p><br></tr></td>\n" +
                            "        </table>\n" +
                            "        \n" +
                            "    </body>\n" +
                            "\n" +
                            "</html>";
        
        JTextPane jtp = new JTextPane();
        jtp.setContentType("text/html");
        jtp.setText(reportText);
        try {
            this.setAlwaysOnTop(false);
            jtp.print();
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(this, "Unable to Print Report Try Again","Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemSalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemSalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemSalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemSalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemSalesReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel StockReportClose;
    private javax.swing.JButton btnItemSalesReportClear;
    private javax.swing.JButton btnItemSalesReportPrint;
    private javax.swing.JButton btnItemSalesReportSearch;
    private javax.swing.JButton btnItemSalesReportViewAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private view.PanelBorder panelBorder1;
    private javax.swing.JTable tblItemSalesReport;
    private javax.swing.JLabel txtItemName;
    private javax.swing.JTextField txtItemNumber;
    private com.toedter.calendar.JDateChooser txtItemSalesReportFromDate;
    private com.toedter.calendar.JDateChooser txtItemSalesReportToDate;
    // End of variables declaration//GEN-END:variables
}
