/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author malith
 */
public class Splash extends javax.swing.JFrame {

    /**
     * Creates new form SplashView
     */
    public Splash() {
        initComponents();
        setBackground(new Color (0,0,0,0)); 
        
        
    }
    
    
     class PanelBorder extends JPanel{
    
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        super.paintComponent(grphcs);
    }
 }
     
      class PanelGradient extends JPanel{
        
      
        protected void paintChildren(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g = new GradientPaint(0, 0, Color.decode("#093637"), 0, getHeight(), Color.decode("#44A08D"));
        g2.setPaint(g);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        //g2.fillRect(getWidth() - 20, 0, getWidth(), getHeight());
        super.paintChildren(grphcs);
    
    }   
        
    }

     
      public void start(){
        try {
            for(int i=0; i<=100; i++)
            {
                
                
                if(i==0){
                txtSplashConnection.setText("Loading ");
                } 
                if(i==5){
                txtSplashConnection.setText("Loading .");
                }
                if(i==10){ 
                txtSplashConnection.setText("Loading . .");
                }
                if(i==20){ 
                txtSplashConnection.setText("Loading . . .");
                }
                if(i==25){
                txtSplashConnection.setText("Loading ");
                } 
                if(i==30){ 
                txtSplashConnection.setText("Loading . ");
                }
                if(i==40){ 
                txtSplashConnection.setText("Loading . .");
                }
                if(i==50){ 
                txtSplashConnection.setText("Loading . . .");
                }
                if(i==55){
                txtSplashConnection.setText("Loading ");
                } 
                if(i==60){ 
                txtSplashConnection.setText("Loading .");
                }
                if(i==70){ 
                txtSplashConnection.setText("Loading . .");
                }
                if(i==80){ 
                txtSplashConnection.setText("Loading . . .");
                }
                if(i==90){ 
                txtSplashConnection.setText("Loading . . . ");
                }
            
                Thread.sleep(40);
                splashProgressBar.setValue(i);
                splashPresentage.setText(Integer.toString(i)+"%");
                
            }
            //Runtime runTime = Runtime.getRuntime();
            //Process process1 = runTime.exec("src/lib/Wampserver.bat");
            
            
            
            this.dispose(); 
            new Login().setVisible(true);
          
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),"Error Found!", JOptionPane.ERROR_MESSAGE);
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSplash = new PanelGradient();
        jLabel1 = new javax.swing.JLabel();
        splashProgressBar = new javax.swing.JProgressBar();
        txtSplashConnection = new javax.swing.JLabel();
        splashPresentage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        PanelSplash.setBackground(new java.awt.Color(0, 102, 102));
        PanelSplash.setOpaque(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoArt.png"))); // NOI18N

        splashProgressBar.setBackground(new java.awt.Color(255, 255, 255));
        splashProgressBar.setForeground(new java.awt.Color(153, 153, 153));
        splashProgressBar.setBorder(null);

        txtSplashConnection.setBackground(new java.awt.Color(255, 255, 255));
        txtSplashConnection.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSplashConnection.setForeground(new java.awt.Color(255, 255, 255));
        txtSplashConnection.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtSplashConnection.setText(" ");

        splashPresentage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        splashPresentage.setForeground(new java.awt.Color(255, 255, 255));
        splashPresentage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout PanelSplashLayout = new javax.swing.GroupLayout(PanelSplash);
        PanelSplash.setLayout(PanelSplashLayout);
        PanelSplashLayout.setHorizontalGroup(
            PanelSplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSplashLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelSplashLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(splashProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                    .addGroup(PanelSplashLayout.createSequentialGroup()
                        .addComponent(txtSplashConnection, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(splashPresentage, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelSplashLayout.setVerticalGroup(
            PanelSplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSplashLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addGap(23, 23, 23)
                .addGroup(PanelSplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(splashPresentage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSplashConnection, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(splashProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelSplash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelSplash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowDeactivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelSplash;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel splashPresentage;
    private javax.swing.JProgressBar splashProgressBar;
    private javax.swing.JLabel txtSplashConnection;
    // End of variables declaration//GEN-END:variables
}
