/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;

/**
 *
 * @author malith
 */
public class StaticSalesReportMenu extends javax.swing.JFrame {

    /**
     * Creates new form StaticSalesReportMenu
     */
    public StaticSalesReportMenu() {
        initComponents();
        setBackground(new Color (0,0,0,0));
        
    }
    private String username = "";
    public void getUserDetails(String uName)
    {
        username = uName;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder = new view.PanelBorder();
        btnAnnualSalesReport = new javax.swing.JLabel();
        btnMonthlySalesReport = new javax.swing.JLabel();
        btnDailySalesReport = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        StaticSalesReportMenuClose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panelBorder.setBackground(new java.awt.Color(255, 255, 255));

        btnAnnualSalesReport.setBackground(new java.awt.Color(204, 204, 204));
        btnAnnualSalesReport.setForeground(new java.awt.Color(255, 255, 255));
        btnAnnualSalesReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAnnualSalesReport.setText("Annual Sales Report");
        btnAnnualSalesReport.setOpaque(true);
        btnAnnualSalesReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnnualSalesReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAnnualSalesReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAnnualSalesReportMouseExited(evt);
            }
        });

        btnMonthlySalesReport.setBackground(new java.awt.Color(204, 204, 204));
        btnMonthlySalesReport.setForeground(new java.awt.Color(255, 255, 255));
        btnMonthlySalesReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMonthlySalesReport.setText("Monthly Sales Report");
        btnMonthlySalesReport.setOpaque(true);
        btnMonthlySalesReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMonthlySalesReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMonthlySalesReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMonthlySalesReportMouseExited(evt);
            }
        });

        btnDailySalesReport.setBackground(new java.awt.Color(204, 204, 204));
        btnDailySalesReport.setForeground(new java.awt.Color(255, 255, 255));
        btnDailySalesReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDailySalesReport.setText("Daily Sales Report");
        btnDailySalesReport.setOpaque(true);
        btnDailySalesReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDailySalesReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDailySalesReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDailySalesReportMouseExited(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Report Type");

        StaticSalesReportMenuClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/closeLogin.png"))); // NOI18N
        StaticSalesReportMenuClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StaticSalesReportMenuCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBorderLayout = new javax.swing.GroupLayout(panelBorder);
        panelBorder.setLayout(panelBorderLayout);
        panelBorderLayout.setHorizontalGroup(
            panelBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorderLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(StaticSalesReportMenuClose)
                .addContainerGap())
            .addGroup(panelBorderLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDailySalesReport, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMonthlySalesReport, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnnualSalesReport, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        panelBorderLayout.setVerticalGroup(
            panelBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(StaticSalesReportMenuClose))
                .addGap(41, 41, 41)
                .addComponent(btnAnnualSalesReport, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMonthlySalesReport, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDailySalesReport, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnAnnualSalesReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnnualSalesReportMouseClicked
        AnnualSalesReport f = new AnnualSalesReport();
        f.setUserName(username);
        f.setVisible(true);
        
        
        this.dispose();
        
    }//GEN-LAST:event_btnAnnualSalesReportMouseClicked

    private void btnAnnualSalesReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnnualSalesReportMouseEntered
        btnAnnualSalesReport.setBackground(Color.GRAY);
    }//GEN-LAST:event_btnAnnualSalesReportMouseEntered

    private void btnAnnualSalesReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnnualSalesReportMouseExited
        btnAnnualSalesReport.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnAnnualSalesReportMouseExited

    private void btnMonthlySalesReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMonthlySalesReportMouseClicked
        MonthlySalesReport f = new MonthlySalesReport();
        f.setUserName(username);
        f.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_btnMonthlySalesReportMouseClicked

    private void btnMonthlySalesReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMonthlySalesReportMouseEntered
        btnMonthlySalesReport.setBackground(Color.GRAY);
    }//GEN-LAST:event_btnMonthlySalesReportMouseEntered

    private void btnMonthlySalesReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMonthlySalesReportMouseExited
        btnMonthlySalesReport.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnMonthlySalesReportMouseExited

    private void btnDailySalesReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDailySalesReportMouseClicked
        DailySalesReport f = new DailySalesReport();
        f.setUserName(username);
        f.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnDailySalesReportMouseClicked

    private void btnDailySalesReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDailySalesReportMouseEntered
        btnDailySalesReport.setBackground(Color.GRAY);
    }//GEN-LAST:event_btnDailySalesReportMouseEntered

    private void btnDailySalesReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDailySalesReportMouseExited
        btnDailySalesReport.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnDailySalesReportMouseExited

    private void StaticSalesReportMenuCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StaticSalesReportMenuCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_StaticSalesReportMenuCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaticSalesReportMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaticSalesReportMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaticSalesReportMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaticSalesReportMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaticSalesReportMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel StaticSalesReportMenuClose;
    private javax.swing.JLabel btnAnnualSalesReport;
    private javax.swing.JLabel btnDailySalesReport;
    private javax.swing.JLabel btnMonthlySalesReport;
    private javax.swing.JLabel jLabel4;
    private view.PanelBorder panelBorder;
    // End of variables declaration//GEN-END:variables
}
