/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Database;
import java.awt.Color;
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author malith
 */
public class StockReport extends javax.swing.JFrame {

    /**
     * Creates new form StockReport
     */
    public StockReport() {
        initComponents();
        setBackground(new Color (0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder = new view.PanelBorder();
        StockReportClose = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbStockReportSearchBy = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtStockReportSearchBy = new javax.swing.JTextField();
        btnStockReportSearchBySearch = new javax.swing.JButton();
        btnStockReportSearchByClear = new javax.swing.JButton();
        btnStockReportSearchByViewAll = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStockReport = new javax.swing.JTable();
        btnStockReportPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panelBorder.setBackground(new java.awt.Color(255, 255, 255));

        StockReportClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/closeLogin.png"))); // NOI18N
        StockReportClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StockReportCloseMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("   Stock Report ");

        cmbStockReportSearchBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select Item-", "Item Number", "Item Name" }));

        jLabel4.setText("Search By");

        btnStockReportSearchBySearch.setBackground(new java.awt.Color(51, 153, 255));
        btnStockReportSearchBySearch.setForeground(new java.awt.Color(255, 255, 255));
        btnStockReportSearchBySearch.setText("Search");
        btnStockReportSearchBySearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockReportSearchBySearchActionPerformed(evt);
            }
        });

        btnStockReportSearchByClear.setBackground(new java.awt.Color(255, 0, 0));
        btnStockReportSearchByClear.setForeground(new java.awt.Color(255, 255, 255));
        btnStockReportSearchByClear.setText("Clear");
        btnStockReportSearchByClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockReportSearchByClearActionPerformed(evt);
            }
        });

        btnStockReportSearchByViewAll.setBackground(new java.awt.Color(0, 102, 102));
        btnStockReportSearchByViewAll.setForeground(new java.awt.Color(255, 255, 255));
        btnStockReportSearchByViewAll.setText("View All");
        btnStockReportSearchByViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockReportSearchByViewAllActionPerformed(evt);
            }
        });

        tblStockReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Number", "Item Name", "Qty In Hand", "Qty Purchased", "Qty Return", "Qty Damaged"
            }
        ));
        jScrollPane1.setViewportView(tblStockReport);

        btnStockReportPrint.setBackground(new java.awt.Color(51, 51, 255));
        btnStockReportPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnStockReportPrint.setText("Print");
        btnStockReportPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockReportPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBorderLayout = new javax.swing.GroupLayout(panelBorder);
        panelBorder.setLayout(panelBorderLayout);
        panelBorderLayout.setHorizontalGroup(
            panelBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorderLayout.createSequentialGroup()
                .addContainerGap(954, Short.MAX_VALUE)
                .addGroup(panelBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorderLayout.createSequentialGroup()
                        .addComponent(StockReportClose)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorderLayout.createSequentialGroup()
                        .addComponent(btnStockReportPrint)
                        .addGap(124, 124, 124))))
            .addGroup(panelBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBorderLayout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addGroup(panelBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1114, Short.MAX_VALUE)
                        .addGroup(panelBorderLayout.createSequentialGroup()
                            .addGap(91, 91, 91)
                            .addGroup(panelBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 947, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelBorderLayout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34)
                                    .addComponent(cmbStockReportSearchBy, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(76, 76, 76)
                                    .addComponent(txtStockReportSearchBy, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnStockReportSearchBySearch)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnStockReportSearchByClear)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnStockReportSearchByViewAll)))
                            .addGap(58, 58, 58)))
                    .addGap(27, 27, 27)))
        );
        panelBorderLayout.setVerticalGroup(
            panelBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StockReportClose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 569, Short.MAX_VALUE)
                .addComponent(btnStockReportPrint)
                .addGap(19, 19, 19))
            .addGroup(panelBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBorderLayout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(78, 78, 78)
                    .addGroup(panelBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(cmbStockReportSearchBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtStockReportSearchBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnStockReportSearchBySearch)
                        .addComponent(btnStockReportSearchByClear)
                        .addComponent(btnStockReportSearchByViewAll))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(56, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void StockReportCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockReportCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_StockReportCloseMouseClicked

    private void btnStockReportSearchByClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockReportSearchByClearActionPerformed
        // TODO add your handling code here:
        StockReport f = new StockReport();
        f.setVisible(true);
        f.setusername(username);
        this.dispose();
    }//GEN-LAST:event_btnStockReportSearchByClearActionPerformed

    private void btnStockReportSearchByViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockReportSearchByViewAllActionPerformed
        // TODO add your handling code here:
        cmbStockReportSearchBy.setSelectedIndex(0);
        txtStockReportSearchBy.setText("");
        loadTableData(null,null);
        if(tblStockReport.getRowCount()<0)
        {
            JOptionPane.showMessageDialog(this, "No Data Found","Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnStockReportSearchByViewAllActionPerformed

    private void btnStockReportSearchBySearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockReportSearchBySearchActionPerformed
        // TODO add your handling code here:
        if(cmbStockReportSearchBy.getSelectedIndex()==0 || txtStockReportSearchBy.getText()==null)
        {
            JOptionPane.showMessageDialog(this, "Select Filter to search or Enter Keyword to search","Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            String filter = "";
            if(cmbStockReportSearchBy.getSelectedIndex()==1)
            {
                filter = "INO";
            }
            if(cmbStockReportSearchBy.getSelectedIndex()==2)
            {
                filter = "IName";
            }
            loadTableData(filter,txtStockReportSearchBy.getText());
            
        }
    }//GEN-LAST:event_btnStockReportSearchBySearchActionPerformed

    private String username="";
    public void setusername(String uname)
    {
        username = uname;
    }
    private void btnStockReportPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockReportPrintActionPerformed
        // TODO add your handling code here:
        if(tblStockReport.getRowCount()<=0)
        {
            JOptionPane.showMessageDialog(this, "Report Data Seems Empty Printing not Available","Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            String aboutText = "";
            if(txtStockReportSearchBy.getText().equals(""))
            {
                
                aboutText = "<tr style=\"border : solid 1pt #000000; border-collapse: collapse;\"> <td><p></p></td> <td><p></p></td> <td><p></p></td> <td><p></p></td> </tr>\n";
            }
            else
            {
                if(cmbStockReportSearchBy.getSelectedIndex()==1)
                {
                    aboutText = "<tr style=\"border : solid 1pt #000000; border-collapse: collapse;\"> <td><p>Search Filter</p></td> <td><p>Item Number</p></td> <td><p></p></td> <td><p></p></td> </tr>\n";
                }
                if(cmbStockReportSearchBy.getSelectedIndex()==2)
                {
                    aboutText = "<tr style=\"border : solid 1pt #000000; border-collapse: collapse;\"> <td><p>Search Filter</p></td> <td><p>Item Name</p></td> <td><p></p></td> <td><p></p></td> </tr>\n";
                }
            }
            this.setAlwaysOnTop(false);
            printReport(aboutText);
        }        
    }//GEN-LAST:event_btnStockReportPrintActionPerformed

    private void printReport(String about)
    {
        Date now = new Date();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String itemData = "";
        int totqtyInHand = 0;
        int totqtyPurchased = 0;
        int totrts = 0;
        int totdamages = 0;
        for(int c=0; c<tblStockReport.getRowCount();c++)
        {
            totqtyInHand = totqtyInHand + Integer.parseInt(tblStockReport.getValueAt(c, 2).toString());
            totqtyPurchased = totqtyPurchased + Integer.parseInt(tblStockReport.getValueAt(c, 3).toString());
            totrts = totrts + Integer.parseInt(tblStockReport.getValueAt(c, 4).toString());
            totdamages = totdamages + Integer.parseInt(tblStockReport.getValueAt(c, 5).toString());
            if(itemData.equals(""))
            {
                itemData = "<tr><td><p>"+tblStockReport.getValueAt(c, 0).toString()+"</p></td><td><p>"+tblStockReport.getValueAt(c, 1).toString()+"</p></td><td><p>"+tblStockReport.getValueAt(c, 2).toString()+"</p></td><td><p>"+tblStockReport.getValueAt(c, 3).toString()+"</p></td><td><p>"+tblStockReport.getValueAt(c, 4).toString()+"</p></td><td><p>"+tblStockReport.getValueAt(c, 5).toString()+"</p></td></tr>\n";
            }  
            else
            {
                itemData = itemData + "<tr><td><p>"+tblStockReport.getValueAt(c, 0).toString()+"</p></td><td><p>"+tblStockReport.getValueAt(c, 1).toString()+"</p></td><td><p>"+tblStockReport.getValueAt(c, 2).toString()+"</p></td><td><p>"+tblStockReport.getValueAt(c, 3).toString()+"</p></td><td><p>"+tblStockReport.getValueAt(c, 4).toString()+"</p></td><td><p>"+tblStockReport.getValueAt(c, 5).toString()+"</p></td></tr>\n";
            }
        }
        String reportText = "<html>\n" +
                            "    <head>\n" +
                            "        <style>\n" +
                            "            p{font-family: 'Times New Roman', Times, serif;font-size: 11pt; text-align: left;}\n" +
                            //"            td {border : solid 1pt #000000; border-collapse: collapse;}\n" +
                            "            table{border : solid 1pt #000000; border-collapse: collapse;}\n" +
                            "        </style>\n" +
                            "    </head>\n" +
                            "    <body>\n" +
                            "        <table style=\"width: 100%;\">\n" +
                            "            <tr><td><h1 style=\"font-family: 'Times New Roman', Times, serif; font-size: 18pt; text-align: center;\">Stock Report</h1></td></tr>\n" +
                            "            <tr aria-rowspan=\"3\">\n" +
                            "                <td><p>Multi Engineering Services Lanka Private Limited<br>No.466/7A Thapowanaya Road, Aggona<br>Sri Lanka.<br>Tel : 0112 794 959, 0114 558 559</p></td>\n" +
                            "            </tr>\n" +
                            //"            <tr><td><p style=\"text-align: center;\">Stock Report<!--report name--></p></td></tr>\n" +
                            "\n" +
                            "            <!--report header details starts here-->\n" +
                            "            <tr>\n" +
                            "                <td>\n" +
                            "                    <table style=\"width: 100%;\">\n" +
                            "                        <tr style=\"border : solid 1pt #000000; border-collapse: collapse;\"> <td><p>Generated By,</p></td> <td><p>"+username+"</p></td> <td><p>Date : </p></td> <td><p>"+df.format(now)+"</p></td> </tr>\n" +
                            "                        "+about+"" +
                            "                    </table>\n" +
                            "                </td>\n" +
                            "            </tr>\n" +
                            "            <tr><td style=\"height: 12pt;\"><p></p></td></tr>\n" +
                            "\n" +
                            "            <!--data table starts here-->\n" +
                            "            <tr>\n" +
                            "                <td>\n" +
                            "                    <table style=\"width: 100%;\">\n" +
                            "                        <tr style=\"border : solid 1pt #000000; border-collapse: collapse;\"><td ><p>Item ID</p></td><td><p>Item Name</p></td><td><p>Qty In Hand</p></td><td><p>Qty Purchased</p></td><td><p>Total Returns</p></td><td><p>Total Damages</p></td></tr>\n" +
                            "                        <!--item data comes here!-->\n" +
                            "                       "+itemData+" " +
                            "\n" +
                            "                        <!--finishes here-->\n" +
                            "                        <tr><td colspan=\"2\"><p style=\"text-align: right;\">Total : </p></td><td><p>"+totqtyInHand+"</p></td><td><p>"+totqtyPurchased+"</p></td><td><p>"+totrts+"</p></td><td><p>"+totdamages+"</p></td></tr>\n" +
                            "                    </table>\n" +
                            "                </td>\n" +
                            "            </tr>\n" +
                            "\n" +
                            "            <tr><td><br><p style=\"text-align: right;\">Certified by,<br><br>-----------------------</p><br></tr></td>\n" +
                            "        </table>\n" +
                            "        \n" +
                            "    </body>\n" +
                            "\n" +
                            "</html>";
        
        JTextPane jtp = new JTextPane();
        jtp.setContentType("text/html");
        jtp.setText(reportText);
        try {
            jtp.print();
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(this, "Unable to Print Report Try Again","Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void loadTableData(String filter,String searchString)
    {
        DefaultTableModel tmodel = (DefaultTableModel)tblStockReport.getModel();
        tmodel.setRowCount(0);
        Database db = new Database();
        ResultSet rs = null;
        ResultSet rs2 = null;
        ResultSet rs3 = null;
        ResultSet rs4 = null;
        ResultSet rs5 = null;
        ResultSet rs6 = null;
        
        if(filter == null && searchString == null)
        {
            rs = db.selectData("SELECT * FROM tb_item");
            if(rs != null)
            {                
                try {
                    while(rs.next())
                    {
                        String ino = String.valueOf(rs.getInt("INO"));
                        String iname = rs.getString("IName");
                        String rQty = String.valueOf(rs.getInt("QtyInHand"));
                        String purchacedQty = "";
                        int cusReturn = 0;
                        int dealerReturn =0;
                        int cusDamaged = 0;
                        int dealerDamaged =0;
                        
                        rs2 = db.selectData("select sum(QtyPurchased) as qtyPurchased from tb_itemininvoice where INO = "+ino+" ");
                        while(rs2.next())
                        {
                            purchacedQty = String.valueOf(rs2.getInt("qtyPurchased"));
                        }
                        
                        rs3 = db.selectData("select sum(qty) as customerreturn from tb_customerreturn where INO = "+ino+" AND remark = 'Item Return'");
                        while(rs3.next())
                        {
                            cusReturn = rs3.getInt("customerreturn");
                        }
                        rs4 = db.selectData("select sum(qty) as dealerreturn from tb_dealerreturn where INO = "+ino+" AND remark = 'Item Return'");
                        while(rs4.next())
                        {
                            dealerReturn = rs4.getInt("dealerreturn");
                        }
                        
                        rs5 = db.selectData("select sum(qty) as customerreturn from tb_customerreturn where INO = "+ino+" AND remark = 'Damaged'");
                        while(rs5.next())
                        {
                            cusDamaged = rs5.getInt("customerreturn");
                        }
                        rs6 = db.selectData("select sum(qty) as dealerreturn from tb_dealerreturn where INO = "+ino+" AND remark = 'Damaged'");
                        while(rs6.next())
                        {
                            dealerDamaged = rs6.getInt("dealerreturn");
                        }
                        
                        String tbData[] = {ino,iname,rQty,purchacedQty,""+(cusReturn+dealerReturn),""+(cusDamaged+dealerDamaged)};
                        tmodel.addRow(tbData);
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage()+" Unable to load data try again", "Error", JOptionPane.ERROR_MESSAGE);
                } catch (NullPointerException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage()+" Unable to load data try again", "Error", JOptionPane.ERROR_MESSAGE);
                }catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage()+" Unable to load data try again", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "No Data Found","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        if(filter != null && searchString != null)
        {
            
            rs = db.selectData("SELECT * FROM `tb_item` WHERE "+filter+" LIKE '%"+searchString+"%'");
            if(rs != null)
            {                
                try {
                    while(rs.next())
                    {
                        String ino = String.valueOf(rs.getInt("INO"));
                        String iname = rs.getString("IName");
                        String rQty = String.valueOf(rs.getInt("QtyInHand"));
                        String purchacedQty = "";
                        int cusReturn = 0;
                        int dealerReturn =0;
                        int cusDamaged = 0;
                        int dealerDamaged =0;
                        
                        rs2 = db.selectData("select sum(QtyPurchased) as qtyPurchased from tb_itemininvoice where INO = "+ino+" ");
                        while(rs2.next())
                        {
                            purchacedQty = String.valueOf(rs2.getInt("qtyPurchased"));
                        }
                        
                        rs3 = db.selectData("select sum(qty) as customerreturn from tb_customerreturn where INO = "+ino+" AND remark = 'Item Return'");
                        while(rs3.next())
                        {
                            cusReturn = rs3.getInt("customerreturn");
                        }
                        rs4 = db.selectData("select sum(qty) as dealerreturn from tb_dealerreturn where INO = "+ino+" AND remark = 'Item Return'");
                        while(rs4.next())
                        {
                            dealerReturn = rs4.getInt("dealerreturn");
                        }
                        
                        rs5 = db.selectData("select sum(qty) as customerreturn from tb_customerreturn where INO = "+ino+" AND remark = 'Damaged'");
                        while(rs5.next())
                        {
                            cusDamaged = rs5.getInt("customerreturn");
                        }
                        rs6 = db.selectData("select sum(qty) as dealerreturn from tb_dealerreturn where INO = "+ino+" AND remark = 'Damaged'");
                        while(rs6.next())
                        {
                            dealerDamaged = rs6.getInt("dealerreturn");
                        }
                        
                        String tbData[] = {ino,iname,rQty,purchacedQty,""+(cusReturn+dealerReturn),""+(cusDamaged+dealerDamaged)};
                        tmodel.addRow(tbData);
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage()+" Unable to load data try again", "Error", JOptionPane.ERROR_MESSAGE);
                } catch (NullPointerException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage()+" Unable to load data try again", "Error", JOptionPane.ERROR_MESSAGE);
                }catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage()+" Unable to load data try again", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "No Data Found","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        if(tblStockReport.getRowCount()<0)
        {
            JOptionPane.showMessageDialog(this, "No Data Found","Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel StockReportClose;
    private javax.swing.JButton btnStockReportPrint;
    private javax.swing.JButton btnStockReportSearchByClear;
    private javax.swing.JButton btnStockReportSearchBySearch;
    private javax.swing.JButton btnStockReportSearchByViewAll;
    private javax.swing.JComboBox<String> cmbStockReportSearchBy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private view.PanelBorder panelBorder;
    private javax.swing.JTable tblStockReport;
    private javax.swing.JTextField txtStockReportSearchBy;
    // End of variables declaration//GEN-END:variables
}
