/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Database;
import java.awt.AlphaComposite;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import model.User;

/**
 *
 * @author malith
 */
public class StockAdjusment extends javax.swing.JFrame {

    /**
     * Creates new form StockAdjusment
     */
    public StockAdjusment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelStockAdjusment = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        StockAdjusmentContent = new javax.swing.JPanel();
        btnStkAdjusmentItemNo = new javax.swing.JLabel();
        btnStkAdjusmentItemName = new javax.swing.JLabel();
        btnStkAdjusmentDate = new javax.swing.JLabel();
        btnStkAdjusmentStockInHand = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnStkAdjusmentNewStock = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnStkAdjusmentRemark = new javax.swing.JTextField();
        btnStkAdjusmentSave = new javax.swing.JButton();
        btnStkAdjusmentCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImages(null);
        setPreferredSize(new java.awt.Dimension(800, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 400));

        PanelStockAdjusment.setBackground(new java.awt.Color(0, 102, 102));
        PanelStockAdjusment.setPreferredSize(new java.awt.Dimension(800, 400));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Stock Adjusment");
        jLabel1.setOpaque(true);

        StockAdjusmentContent.setBackground(new java.awt.Color(204, 204, 204));
        StockAdjusmentContent.setPreferredSize(new java.awt.Dimension(800, 305));

        btnStkAdjusmentItemNo.setText("Item No - ");

        btnStkAdjusmentItemName.setText("Item Name - ");

        btnStkAdjusmentDate.setText("Date");

        btnStkAdjusmentStockInHand.setText("Stock In Hand - ");

        jLabel6.setText("Enter New Stock");

        btnStkAdjusmentNewStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnStkAdjusmentNewStockKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnStkAdjusmentNewStockKeyTyped(evt);
            }
        });

        jLabel7.setText("Remark");

        btnStkAdjusmentRemark.setEditable(false);

        btnStkAdjusmentSave.setBackground(new java.awt.Color(0, 102, 102));
        btnStkAdjusmentSave.setForeground(new java.awt.Color(255, 255, 255));
        btnStkAdjusmentSave.setText("Save");
        btnStkAdjusmentSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStkAdjusmentSaveActionPerformed(evt);
            }
        });

        btnStkAdjusmentCancel.setBackground(new java.awt.Color(255, 0, 0));
        btnStkAdjusmentCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnStkAdjusmentCancel.setText("Cancel");
        btnStkAdjusmentCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStkAdjusmentCancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout StockAdjusmentContentLayout = new javax.swing.GroupLayout(StockAdjusmentContent);
        StockAdjusmentContent.setLayout(StockAdjusmentContentLayout);
        StockAdjusmentContentLayout.setHorizontalGroup(
            StockAdjusmentContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StockAdjusmentContentLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(StockAdjusmentContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addComponent(btnStkAdjusmentStockInHand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStkAdjusmentItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStkAdjusmentItemNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(StockAdjusmentContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StockAdjusmentContentLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(btnStkAdjusmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StockAdjusmentContentLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(StockAdjusmentContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnStkAdjusmentNewStock, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(btnStkAdjusmentRemark))))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StockAdjusmentContentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnStkAdjusmentSave)
                .addGap(18, 18, 18)
                .addComponent(btnStkAdjusmentCancel)
                .addGap(38, 38, 38))
        );

        StockAdjusmentContentLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnStkAdjusmentCancel, btnStkAdjusmentSave});

        StockAdjusmentContentLayout.setVerticalGroup(
            StockAdjusmentContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StockAdjusmentContentLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(StockAdjusmentContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStkAdjusmentItemNo)
                    .addComponent(btnStkAdjusmentDate))
                .addGap(22, 22, 22)
                .addComponent(btnStkAdjusmentItemName)
                .addGap(22, 22, 22)
                .addComponent(btnStkAdjusmentStockInHand)
                .addGap(22, 22, 22)
                .addGroup(StockAdjusmentContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btnStkAdjusmentNewStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(StockAdjusmentContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStkAdjusmentRemark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(33, 33, 33)
                .addGroup(StockAdjusmentContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStkAdjusmentSave)
                    .addComponent(btnStkAdjusmentCancel))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout PanelStockAdjusmentLayout = new javax.swing.GroupLayout(PanelStockAdjusment);
        PanelStockAdjusment.setLayout(PanelStockAdjusmentLayout);
        PanelStockAdjusmentLayout.setHorizontalGroup(
            PanelStockAdjusmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelStockAdjusmentLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
            .addComponent(StockAdjusmentContent, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
        );
        PanelStockAdjusmentLayout.setVerticalGroup(
            PanelStockAdjusmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelStockAdjusmentLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StockAdjusmentContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelStockAdjusment, 816, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelStockAdjusment, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(832, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStkAdjusmentCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStkAdjusmentCancelMouseClicked
           
        this.dispose();
    }//GEN-LAST:event_btnStkAdjusmentCancelMouseClicked

    private void btnStkAdjusmentNewStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnStkAdjusmentNewStockKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStkAdjusmentNewStockKeyTyped

    
 
   

    
    
    private void btnStkAdjusmentNewStockKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnStkAdjusmentNewStockKeyReleased
        // TODO add your handling code here:
        Pattern discountreg = Pattern.compile("^[0-9]*$");
        Matcher mdiscountreg = discountreg.matcher(btnStkAdjusmentNewStock.getText());
        
        if(!mdiscountreg.find()){
            JOptionPane.showMessageDialog(this, "You must entered numbers only!","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        String oldStockString  = btnStkAdjusmentStockInHand.getText();
        String newStockString = btnStkAdjusmentNewStock.getText();
        
        if((btnStkAdjusmentNewStock.getText()).equals(""))
        {
            btnStkAdjusmentRemark.setText("");
        }
        
        if(!oldStockString.equals("") && !newStockString.equals(""))
        {
            String oStock[] = oldStockString.split("-");
            int oldStock = Integer.parseInt(oStock[1]);
            int newStock = Integer.parseInt(newStockString);
            if(oldStock<newStock)
            {
                btnStkAdjusmentRemark.setText("Stock Addition");
            }
            if(oldStock>newStock)
            {
                btnStkAdjusmentRemark.setText("Stock Deduction");
            }
        }               
    }//GEN-LAST:event_btnStkAdjusmentNewStockKeyReleased

    private void btnStkAdjusmentSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStkAdjusmentSaveActionPerformed
        // TODO add your handling code here:
        String oldStockString  = btnStkAdjusmentStockInHand.getText();
        String oStock[] = oldStockString.split("-");
        
        String dateString = btnStkAdjusmentDate.getText();
        String date[] = dateString.split(":");
        
        String itemNumberString = btnStkAdjusmentItemNo.getText();
        String itemNumber[] = itemNumberString.split("-");
        
        Database db = new Database();
        int i = db.insertUpdateDelete("INSERT INTO `tb_stockadjustment` VALUES (NULL, '"+itemNumber[1]+"', '"+date[1]+"', '"+btnStkAdjusmentRemark.getText()+"', '"+oStock[1]+"', '"+btnStkAdjusmentNewStock.getText()+"')");
        if(i==1)
        {
            int c = db.insertUpdateDelete("UPDATE `tb_item` SET `Qtyinhand` = '"+btnStkAdjusmentNewStock.getText()+"' WHERE `tb_item`.`INO` = "+itemNumber[1]+"");
            if(c==1)
            {
                User u = new User();                        
                u.recordUserOperation(username, "Item", "Stock Adjustment", btnStkAdjusmentItemNo.getText());
                JOptionPane.showMessageDialog(this, "Item Data Updated Successfully","Done!",JOptionPane.INFORMATION_MESSAGE);
                btnStkAdjusmentNewStock.setText("");
                btnStkAdjusmentRemark.setText("");
                try {
                    setItemData(itemNumber[1]);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Item Data Cannot loaded now repoen the menu","Error!",JOptionPane.ERROR_MESSAGE);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Item Data Not Updated Successfully","Done!",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Cannot Update Data Try Again","Error!",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnStkAdjusmentSaveActionPerformed

    private String username = "";
    public void setUsername(String uName)
    {
        username=uName;
    }
    public void setItemData(String itemNo) throws SQLException
    {
        Database db = new Database();
        ResultSet rs = db.selectData("select * from tb_item where ino = '"+itemNo+"'");
        while(rs.next())
        {
            btnStkAdjusmentItemNo.setText("Item Number-"+itemNo);
            btnStkAdjusmentItemName.setText("Item Name-"+rs.getString("IName"));
            btnStkAdjusmentStockInHand.setText("Stock in Hand-"+String.valueOf(rs.getInt("qtyinhand")));
        }
        DateTimeFormatter df = DateTimeFormatter.ofPattern("yyyy-MM-dd");  
        LocalDateTime now = LocalDateTime.now();
        btnStkAdjusmentDate.setText("Date:"+df.format(now));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockAdjusment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockAdjusment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockAdjusment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockAdjusment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockAdjusment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelStockAdjusment;
    private javax.swing.JPanel StockAdjusmentContent;
    private javax.swing.JButton btnStkAdjusmentCancel;
    private javax.swing.JLabel btnStkAdjusmentDate;
    private javax.swing.JLabel btnStkAdjusmentItemName;
    private javax.swing.JLabel btnStkAdjusmentItemNo;
    private javax.swing.JTextField btnStkAdjusmentNewStock;
    private javax.swing.JTextField btnStkAdjusmentRemark;
    private javax.swing.JButton btnStkAdjusmentSave;
    private javax.swing.JLabel btnStkAdjusmentStockInHand;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
